export default [
  {
    id: "41",
    nom: "Loir-et-Cher",
    slug: "loir-et-cher",
    region: "Centre-Val de Loire",
    intro: "Blois et son château royal, le domaine national de Chambord et son parc forestier de 5440 hectares, Cheverny et son chenil de chasse historique, Chaumont-sur-Loire et son festival international des jardins, Vendôme et la vallée du Loir, Romorantin-Lanthenay porte de la Sologne, le ZooParc de Beauval à Saint-Aignan, les forêts domaniales de Russy, de Boulogne et de Blois, les étangs de Sologne — entre châteaux royaux, forêts giboyeuses et bords de Loire, de bonnes adresses pour voyager avec son chien.",
    seoTitle: "Où aller avec son chien en Loir-et-Cher",
    seoDescription: "Où aller avec son chien en Loir-et-Cher : Blois, Chambord, Cheverny, Chaumont-sur-Loire, Vendôme, Sologne — balades, lacs et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien en Loir-et-Cher",
  },
  {
    id: "37",
    nom: "Indre-et-Loire",
    slug: "indre-et-loire",
    region: "Centre-Val de Loire",
    intro: "Tours et sa vieille ville à colombages, les châteaux de la Loire — Villandry et ses jardins, Chenonceau enjambant le Cher, Amboise et son château royal, Langeais et son donjon médiéval —, Chinon et sa forteresse royale dominant la Vienne, Loches et sa cité royale, la vallée de la Loire classée au patrimoine mondial, les forêts domaniales de Chinon et d'Amboise — entre châteaux royaux, bords de Loire et villages de tuffeau, de bonnes adresses pour voyager avec son chien.",
    seoTitle: "Où aller avec son chien en Indre-et-Loire",
    seoDescription: "Où aller avec son chien en Indre-et-Loire : Tours, châteaux de la Loire, Chenonceau, Amboise, Chinon, Loches — balades, lacs et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien en Indre-et-Loire",
  },
  {
    id: "61",
    nom: "Orne",
    slug: "orne",
    region: "Normandie",
    intro: "Alençon et sa dentelle, le haras national du Pin, la forêt d'Écouves et ses hêtraies, le massif des Andaines et la Roche d'Oëtre surplombant la vallée de la Rouvre, Bagnoles-de-l'Orne et son lac, Domfront perché sur son éperon rocheux, Sées et sa cathédrale, le parc naturel régional Normandie-Maine — entre bocage, forêts domaniales et étangs, de bonnes adresses pour voyager avec son chien.",
    seoTitle: "Où aller avec son chien dans l'Orne",
    seoDescription: "Où aller avec son chien dans l'Orne : Alençon, Bagnoles-de-l'Orne, forêt d'Écouves, Roche d'Oëtre, Domfront — balades, lacs et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien dans l'Orne",
  },
  {
    id: "27",
    nom: "Eure",
    slug: "eure",
    region: "Normandie",
    intro: "Giverny et le jardin de Claude Monet, Les Andelys et le Château Gaillard dominant la Seine, Évreux et sa cathédrale, Vernon et ses vieux moulins, la forêt de Lyons et ses hêtraies, le parc naturel régional des Boucles de la Seine Normande côté Eure, Louviers et Pont-Audemer, la vallée de l'Avre et celle de l'Iton — entre méandres de Seine, forêts domaniales et villages normands à colombages, de bonnes adresses pour voyager avec son chien.",
    seoTitle: "Où aller avec son chien dans l'Eure",
    seoDescription: "Où aller avec son chien dans l'Eure : Giverny, Les Andelys, Évreux, Vernon, forêt de Lyons — plages, balades et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien dans l'Eure",
  },
  {
    id: "76",
    nom: "Seine-Maritime",
    slug: "seine-maritime",
    region: "Normandie",
    intro: "Rouen et sa vieille ville à colombages, les falaises d'Étretat et sa fameuse arche, Le Havre et son port reconstruit par Perret, Fécamp et le Palais Bénédictine, Dieppe et sa plage de galets, la Côte d'Albâtre entre Veules-les-Roses et Saint-Valery-en-Caux, la vallée de la Seine et ses boucles, le pays de Caux — entre falaises de craie, grandes plages et villes historiques, de bonnes adresses pour voyager avec son chien.",
    seoTitle: "Où aller avec son chien en Seine-Maritime",
    seoDescription: "Où aller avec son chien en Seine-Maritime : Rouen, Étretat, Le Havre, Fécamp, Dieppe, Côte d'Albâtre — plages, balades et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien en Seine-Maritime",
  },
  {
    id: "50",
    nom: "Manche",
    slug: "manche",
    region: "Normandie",
    intro: "Le Mont-Saint-Michel et sa baie, Cherbourg-en-Cotentin et sa rade, Granville et le cap Lihou, Barneville-Carteret et les îles Chausey, Avranches, Coutances et Saint-Lô, la Hague et ses landes sauvages — entre grandes marées, dunes et bocage normand, de bonnes adresses pour voyager avec son chien.",
    seoTitle: "Où aller avec son chien dans la Manche",
    seoDescription: "Où aller avec son chien dans la Manche : Mont-Saint-Michel, Cherbourg, Granville, Barneville-Carteret, la Hague — plages, balades et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien dans la Manche",
  },
  {
    id: "14",
    nom: "Calvados",
    slug: "calvados",
    region: "Normandie",
    intro: "Deauville et Trouville face à face sur la Côte Fleurie, Honfleur et son Vieux Bassin, Cabourg et sa promenade Marcel-Proust, les plages du Débarquement et les falaises d'Arromanches, Caen et son château ducal, la Suisse Normande et ses gorges de l'Orne — entre grandes plages, bocage et villes historiques, de bonnes adresses pour voyager avec son chien.",
    seoTitle: "Où aller avec son chien dans le Calvados",
    seoDescription: "Où aller avec son chien dans le Calvados : Deauville, Honfleur, Cabourg, Caen, plages du Débarquement, Suisse Normande — plages, balades et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien dans le Calvados",
  },
  {
    id: "35",
    nom: "Ille-et-Vilaine",
    slug: "ille-et-vilaine",
    region: "Bretagne",
    intro: "Saint-Malo intra-muros et sa Côte d'Émeraude, Dinard et la promenade du Clair de Lune, Cancale et la Pointe du Grouin, Rennes et ses parcs, Fougères et sa forêt, Vitré et Combourg, la baie du Mont-Saint-Michel côté breton, Redon au confluent de la Vilaine — entre remparts, plages et campagne intérieure, de bonnes adresses pour voyager avec son chien.",
    seoTitle: "Où aller avec son chien en Ille-et-Vilaine",
    seoDescription: "Où aller avec son chien en Ille-et-Vilaine : Saint-Malo, Dinard, Cancale, Rennes, Fougères, baie du Mont-Saint-Michel — plages, balades et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien en Ille-et-Vilaine",
  },
  {
    id: "56",
    nom: "Morbihan",
    slug: "morbihan",
    region: "Bretagne",
    intro: "Le golfe du Morbihan et ses îles (Île-aux-Moines, Île-d'Arz), Vannes et ses remparts, Carnac et ses alignements mégalithiques, la presqu'île de Quiberon et sa Côte Sauvage, Belle-Île-en-Mer et l'Île de Groix, Lorient et sa rade, Auray, Pontivy et Josselin — entre golfe, grèves et forêts intérieures, de bonnes adresses pour voyager avec son chien.",
    seoTitle: "Où aller avec son chien dans le Morbihan",
    seoDescription: "Où aller avec son chien dans le Morbihan : golfe du Morbihan, Vannes, Carnac, Quiberon, Belle-Île, Lorient, Josselin — plages, balades et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien dans le Morbihan",
  },
  {
    id: "22",
    nom: "Côtes-d'Armor",
    slug: "cotes-darmor",
    region: "Bretagne",
    intro: "La Côte de Granit Rose entre Perros-Guirec, Ploumanac'h et Trégastel, Paimpol et l'Île de Bréhat, la baie de Saint-Brieuc et sa réserve naturelle, Erquy, Pléneuf-Val-André et le Cap Fréhel, Dinan et la vallée de la Rance, le lac de Guerlédan et les forêts d'Avaugour et de la Hunaudaye — entre rochers roses, grèves et forêts intérieures, de bonnes adresses pour voyager avec son chien.",
    seoTitle: "Où aller avec son chien dans les Côtes-d'Armor",
    seoDescription: "Où aller avec son chien dans les Côtes-d'Armor : Perros-Guirec, Paimpol, Dinan, Cap Fréhel, lac de Guerlédan — plages, balades et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien dans les Côtes-d'Armor",
  },
  {
    id: "29",
    nom: "Finistère",
    slug: "finistere",
    region: "Bretagne",
    intro: "La presqu'île de Crozon et ses pointes sur le GR34, Camaret-sur-Mer, Douarnenez, Quimper et l'Odet, Concarneau, Pont-Aven, Brest et sa rade, Carantec, Roscoff, les Monts d'Arrée et leurs lacs, le Pays Bigouden, la Pointe du Raz, les îles de Batz, Ouessant, Molène, Sein et les Glénan — le bout du monde breton, entre plages, sentiers côtiers et bonnes adresses pour voyager avec son chien.",
    seoTitle: "Où aller avec son chien dans le Finistère",
    seoDescription: "Où aller avec son chien dans le Finistère : Crozon, Douarnenez, Quimper, Brest, Pointe du Raz, Monts d'Arrée — plages, lacs, balades et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien dans le Finistère",
  },
  {
    id: "90",
    nom: "Territoire de Belfort",
    slug: "territoire-de-belfort",
    region: "Bourgogne-Franche-Comté",
    intro: "Belfort et sa citadelle Vauban dominée par le Lion de Bartholdi, l'étang des Forges, la base de loisirs du Malsaucy, le massif du Ballon d'Alsace et ses sentiers entre Giromagny et Lepuix, la vallée de la Savoureuse, Delle et sa frontière suisse, Beaucourt — le plus petit département de France métropolitaine, entre citadelle, étangs et contreforts vosgiens, avec de bonnes adresses pour voyager avec son chien.",
    seoTitle: "Où aller avec son chien dans le Territoire de Belfort",
    seoDescription: "Où aller avec son chien dans le Territoire de Belfort : Belfort et sa citadelle, étang des Forges, Malsaucy, Ballon d'Alsace — balades, lacs et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien dans le Territoire de Belfort",
  },
  {
    id: "39",
    nom: "Jura",
    slug: "jura",
    region: "Bourgogne-Franche-Comté",
    intro: "Les cascades du Hérisson, le lac de Vouglans et le lac de Chalain, la cluse de Baume-les-Messieurs classée parmi les plus beaux villages de France, la reculée des Planches-près-Arbois et sa cascade des Tufs, Arbois et son vignoble de vin jaune, Château-Chalon, la station des Rousses et le Haut-Jura, Lons-le-Saunier, Dole et Saint-Claude — un département entre lacs, reculées et vignoble, avec de bonnes adresses pour voyager avec son chien.",
    seoTitle: "Où aller avec son chien dans le Jura : Hérisson, Vouglans",
    seoDescription: "Où aller avec son chien dans le Jura : cascades du Hérisson, lac de Vouglans, Baume-les-Messieurs, Arbois, Château-Chalon — balades, lacs et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien dans le Jura",
  },
  {
    id: "25",
    nom: "Doubs",
    slug: "doubs",
    region: "Bourgogne-Franche-Comté",
    intro: "Besançon et sa citadelle Vauban classée à l'UNESCO, les gorges du Doubs et le saut du Doubs près de Villers-le-Lac, la source et la vallée de la Loue, le lac de Saint-Point et la réserve naturelle du lac de Remoray, le Mont d'Or et la station de Métabief, Pontarlier et le Haut-Doubs, le pays horloger autour de Morteau, Montbéliard — un département entre rivières, lacs de montagne et patrimoine horloger, avec de bonnes adresses pour voyager avec son chien.",
    seoTitle: "Où aller avec son chien dans le Doubs : Besançon, Saut du Doubs",
    seoDescription: "Où aller avec son chien dans le Doubs : Besançon, saut du Doubs, vallée de la Loue, lac de Saint-Point, Métabief — balades, lacs et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien dans le Doubs",
  },
  {
    id: "89",
    nom: "Yonne",
    slug: "yonne",
    region: "Bourgogne-Franche-Comté",
    intro: "Auxerre et ses bords de rivière, Vézelay et sa basilique perchée classée à l'UNESCO, le vignoble de Chablis, les châteaux de Saint-Fargeau et d'Ancy-le-Franc, le canal du Nivernais et le canal de Bourgogne, la vallée du Cousin près d'Avallon, le Morvan yonnais — un département entre vignes, rivières et patrimoine roman, avec de bonnes adresses pour voyager avec son chien.",
    seoTitle: "Où aller avec son chien dans l'Yonne : Auxerre, Vézelay, Chablis",
    seoDescription: "Où aller avec son chien dans l'Yonne : Auxerre, Vézelay, Chablis, canal du Nivernais, vallée du Cousin — balades, lacs et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien dans l'Yonne",
  },
  {
    id: "21",
    nom: "Côte-d'Or",
    slug: "cote-dor",
    region: "Bourgogne-Franche-Comté",
    intro: "Dijon et ses parcs (Colombière, Arquebuse, lac Kir), la Côte viticole et ses Grands Crus (Gevrey-Chambertin, Nuits-Saint-Georges, Vougeot), l'abbaye de Fontenay classée à l'UNESCO, le site d'Alésia, le canal de Bourgogne, l'Auxois et ses châteaux (Châteauneuf, Commarin, Bussy-Rabutin), le Châtillonnais — un département entre vignoble prestigieux et campagne bourguignonne, avec de bonnes adresses pour voyager avec son chien.",
    seoTitle: "Où aller avec son chien en Côte-d'Or : Dijon, Beaune, Alésia",
    seoDescription: "Où aller avec son chien en Côte-d'Or : Dijon, Côte viticole, Fontenay, Alésia, canal de Bourgogne, Auxois — balades, lacs et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien en Côte-d'Or",
  },
  {
    id: "71",
    nom: "Saône-et-Loire",
    slug: "saone-et-loire",
    region: "Bourgogne-Franche-Comté",
    intro: "La Roche de Solutré et son emblématique sentier de crête, l'abbaye de Cluny et son parc, le vignoble du Mâconnais (Solutré-Pouilly, Fuissé) et le Charolais-Brionnais, Autun et sa cascade de Brisecou, la Voie Bleue le long de la Saône, le Mont Beuvray et le site archéologique de Bibracte — un département entre vignes, Bresse et Morvan, avec de bonnes adresses pour voyager avec son chien.",
    seoTitle: "Où aller avec son chien en Saône-et-Loire : Cluny, Mâconnais",
    seoDescription: "Où aller avec son chien en Saône-et-Loire : Roche de Solutré, Cluny, Mâconnais, Autun, Voie Bleue, Bibracte — balades, lacs et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien en Saône-et-Loire",
  },
  {
    id: "58",
    nom: "Nièvre",
    slug: "nievre",
    region: "Bourgogne-Franche-Comté",
    intro: "Nevers et sa cathédrale Saint-Cyr, le pont de la faïencerie et les ateliers de faïence, La Charité-sur-Loire et son prieuré classé à l'UNESCO, le Parc naturel régional du Morvan et le lac des Settons, le canal du Nivernais, les bords de Loire et de l'Allier, Pougues-les-Eaux, Decize au confluent de la Loire et du canal — un département entre Loire, Morvan et patrimoine roman, avec de bonnes adresses pour voyager avec son chien.",
    seoTitle: "Où aller avec son chien dans la Nièvre : Nevers, Morvan",
    seoDescription: "Où aller avec son chien dans la Nièvre : Nevers, La Charité-sur-Loire, Morvan, lac des Settons, canal du Nivernais — balades, lacs et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien dans la Nièvre",
  },
  {
    id: "70",
    nom: "Haute-Saône",
    slug: "haute-saone",
    region: "Bourgogne-Franche-Comté",
    intro: "Vesoul et son lac au pied de la colline de la Motte, Gray et ses bords de Saône, Luxeuil-les-Bains et ses thermes gallo-romains, le Plateau des Mille Étangs autour de Faucogney-et-la-Mer et Mélisey, la vallée de l'Ognon, le village classé de Pesmes, le château de Ray-sur-Saône, Villersexel et Lure — un département entre Saône, étangs et stations thermales, avec de bonnes adresses pour voyager avec son chien.",
    seoTitle: "Où aller avec son chien en Haute-Saône : Vesoul, Mille Étangs",
    seoDescription: "Où aller avec son chien en Haute-Saône : Vesoul, Gray, Luxeuil-les-Bains, Plateau des Mille Étangs, vallée de l'Ognon — balades, lacs et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien en Haute-Saône",
  },
  {
    id: "69",
    nom: "Rhône",
    slug: "rhone",
    region: "Auvergne-Rhône-Alpes",
    intro: "Lyon et ses grands parcs urbains (Tête d'Or, Gerland, Parilly), les Monts du Lyonnais, le vignoble du Beaujolais et ses villages viticoles (Fleurie, Villié-Morgon, Beaujeu), le Grand Parc de Miribel-Jonage et ses plages canines, les berges du Rhône et de la Saône — un département entre métropole animée et campagne beaujolaise, avec de bonnes adresses pour voyager avec son chien.",
    seoTitle: "Où aller avec son chien dans le Rhône : Lyon, Beaujolais",
    seoDescription: "Où aller avec son chien dans le Rhône : Lyon, parcs urbains, Miribel-Jonage, Beaujolais, Monts du Lyonnais — balades, lacs et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien dans le Rhône",
  },
  {
    id: "63",
    nom: "Puy-de-Dôme",
    slug: "puy-de-dome",
    region: "Auvergne-Rhône-Alpes",
    intro: "Clermont-Ferrand et sa cathédrale de pierre noire, la chaîne des Puys classée à l'UNESCO et son volcan emblématique le puy de Dôme, le massif du Sancy et ses lacs de cratère (Pavin, Guéry, Servières, Chambon, Aydat), les gorges de la Sioule et d'Enval, le plateau de Gergovie, Riom et Issoire — un département volcanique au cœur de l'Auvergne, avec de bonnes adresses pour voyager avec son chien.",
    seoTitle: "Où aller avec son chien en Puy-de-Dôme : Clermont-Ferrand, Sancy",
    seoDescription: "Où aller avec son chien en Puy-de-Dôme : Clermont-Ferrand, chaîne des Puys, massif du Sancy, lacs de cratère, gorges d'Enval — balades, lacs et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien en Puy-de-Dôme",
  },
  {
    id: "43",
    nom: "Haute-Loire",
    slug: "haute-loire",
    region: "Auvergne-Rhône-Alpes",
    intro: "Le Puy-en-Velay et sa cathédrale perchée, le rocher Saint-Michel d'Aiguilhe, les volcans du Devès, les gorges de l'Allier et de la Loire, le plateau du Mézenc et son point culminant, le lac du Bouchet — un département volcanique et rural entre Velay et Margeride, avec de bonnes adresses pour voyager avec son chien.",
    seoTitle: "Où aller avec son chien en Haute-Loire : Le Puy-en-Velay, Mézenc",
    seoDescription: "Où aller avec son chien en Haute-Loire : Le Puy-en-Velay, gorges de l'Allier, Mézenc, lac du Bouchet, Devès, Margeride — balades, lacs et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien en Haute-Loire",
  },
  {
    id: "42",
    nom: "Loire",
    slug: "loire",
    region: "Auvergne-Rhône-Alpes",
    intro: "Saint-Étienne et ses friches industrielles reconverties, le Forez et ses monts, le Pilat et son parc naturel régional, Roanne et la plaine roannaise, les gorges de la Loire et le barrage de Grangent — un département méconnu entre moyenne montagne et vallée fluviale, avec de bonnes adresses pour voyager avec son chien.",
    seoTitle: "Où aller avec son chien dans la Loire : Saint-Étienne, Pilat, gorges de la Loire",
    seoDescription: "Où aller avec son chien dans la Loire : Saint-Étienne, monts du Forez, parc du Pilat, gorges de la Loire, barrage de Grangent, Roanne — balades, lacs et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien dans la Loire",
  },
  {
    id: "74",
    nom: "Haute-Savoie",
    slug: "haute-savoie",
    region: "Auvergne-Rhône-Alpes",
    intro: "Annecy et son lac aux eaux turquoise, Chamonix-Mont-Blanc et le massif du Mont-Blanc, le lac Léman entre Évian et Thonon, les grandes stations des Aravis et du Chablais (La Clusaz, Le Grand-Bornand, Morzine, Avoriaz, Samoëns), les gorges du Fier et de la Diosaz — un département entre deux lacs et une haute montagne exigeante sur la réglementation chien (réserve des Aiguilles Rouges, Aiguille du Midi interdites), mais très riche en adresses pour voyager avec son chien.",
    seoTitle: "Où aller avec son chien en Haute-Savoie : Annecy, Chamonix, Léman",
    seoDescription: "Où aller avec son chien en Haute-Savoie : lac d'Annecy, lac Léman, Chamonix-Mont-Blanc, Aravis, Chablais — balades, lacs et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien en Haute-Savoie",
  },
  {
    id: "73",
    nom: "Savoie",
    slug: "savoie",
    region: "Auvergne-Rhône-Alpes",
    intro: "Chambéry et ses Charmettes, le lac du Bourget et Aix-les-Bains, le lac d'Aiguebelette, la Tarentaise et ses grandes stations (Val d'Isère, Tignes, Les Arcs, La Plagne), la Maurienne, le massif des Bauges et le Parc national de la Vanoise — un département montagnard exigeant sur la réglementation chien (cœur du parc national interdit), mais riche en adresses pour voyager avec son chien.",
    seoTitle: "Où aller avec son chien en Savoie : Chambéry, lac du Bourget, Vanoise",
    seoDescription: "Où aller avec son chien en Savoie : lac du Bourget, Aix-les-Bains, Tarentaise, Maurienne, Bauges, Parc national de la Vanoise — balades, lacs et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien en Savoie",
  },
  {
    id: "38",
    nom: "Isère",
    slug: "isere",
    region: "Auvergne-Rhône-Alpes",
    intro: "Grenoble et sa Bastille, le massif de la Chartreuse, le Vercors isérois, l'Oisans et ses glaciers (Alpe d'Huez, Les Deux Alpes), le lac de Paladru, les lacs de Laffrey et le lac de Monteynard-Avignonet et ses passerelles himalayennes — un département alpin d'une grande diversité, entre montagne, lacs et patrimoine, avec de nombreuses adresses pour voyager avec son chien.",
    seoTitle: "Où aller avec son chien en Isère : Grenoble, Vercors, Oisans",
    seoDescription: "Où aller avec son chien en Isère : Grenoble et la Bastille, Chartreuse, Vercors isérois, Oisans, lac de Paladru, lac de Monteynard — balades, lacs et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien en Isère",
  },
  {
    id: "26",
    nom: "Drôme",
    slug: "drome",
    region: "Auvergne-Rhône-Alpes",
    intro: "Valence et la vallée du Rhône, le Vercors drômois et ses gorges, la Drôme provençale entre Nyons et Grignan, les champs de lavande, Die et le Diois, Montélimar — un département aux visages très contrastés entre moyenne montagne et Provence, avec de nombreuses adresses pour voyager avec son chien.",
    seoTitle: "Où aller avec son chien dans la Drôme : Vercors, Nyons, Grignan",
    seoDescription: "Où aller avec son chien dans la Drôme : Vercors drômois, Drôme provençale, Nyons, Grignan, Die, Valence, Montélimar — balades, lacs et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien dans la Drôme",
  },
  {
    id: "15",
    nom: "Cantal",
    slug: "cantal",
    region: "Auvergne-Rhône-Alpes",
    intro: "Le Puy Mary et les volcans cantaliens, Salers et ses maisons de lave, le lac de Saint-Étienne-Cantalès, Aurillac et Saint-Flour, les gorges de la Jordanne et de la Truyère — un département de moyenne montagne volcanique, entre burons, estives et grands espaces pour les balades avec son chien.",
    seoTitle: "Où aller avec son chien dans le Cantal : Puy Mary, Salers, lacs",
    seoDescription: "Où aller avec son chien dans le Cantal : Puy Mary, Salers, lac de Saint-Étienne-Cantalès, gorges de la Jordanne, Aurillac, Saint-Flour — balades, lacs et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien dans le Cantal",
  },
  {
    id: "07",
    nom: "Ardèche",
    slug: "ardeche",
    region: "Auvergne-Rhône-Alpes",
    intro: "Les gorges de l'Ardèche et le Pont d'Arc, Vallon-Pont-d'Arc, les villages de caractère (Balazuc, Vogüé, Labeaume), le Mont Gerbier de Jonc et les Monts d'Ardèche, Privas et Aubenas, la vallée de l'Eyrieux — un grand département de rivières, de gorges et de villages en pierre pour les balades avec son chien.",
    seoTitle: "Où aller avec son chien en Ardèche : gorges, Pont d'Arc, Balazuc",
    seoDescription: "Où aller avec son chien en Ardèche : gorges de l'Ardèche, Pont d'Arc, Vallon-Pont-d'Arc, villages de caractère, Mont Gerbier de Jonc — balades, rivières et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien en Ardèche",
  },
  {
    id: "03",
    nom: "Allier",
    slug: "allier",
    region: "Auvergne-Rhône-Alpes",
    intro: "Moulins et Vichy, la forêt de Tronçais et ses étangs, les gorges de la Sioule, le château de Lapalisse, Montluçon et le canal de Berry — un département rural entre Bourbonnais et Sologne bourbonnaise, avec de grands espaces forestiers pour les balades.",
    seoTitle: "Où aller avec son chien dans l'Allier : Vichy, Moulins, Tronçais",
    seoDescription: "Où aller avec son chien dans l'Allier : Vichy, Moulins, forêt de Tronçais, gorges de la Sioule, Montluçon — balades, lacs et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien dans l'Allier",
  },
  {
    id: "01",
    nom: "Ain",
    slug: "ain",
    region: "Auvergne-Rhône-Alpes",
    intro: "Bourg-en-Bresse et la Bresse, le Bugey et ses lacs (Nantua, Genin), les gorges de l'Ain, la cité médiévale de Pérouges, les étangs de la Dombes et le Pays de Gex aux portes de Genève — un département aux visages très variés entre plaine, rivière et moyenne montagne.",
    seoTitle: "Où aller avec son chien dans l'Ain : Bourg-en-Bresse, Bugey, Pérouges",
    seoDescription: "Où aller avec son chien dans l'Ain : Bourg-en-Bresse, lac de Nantua, Bugey, Pérouges, Dombes, Pays de Gex — balades, plages et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien dans l'Ain",
  },
  {
    id: "23",
    nom: "Creuse",
    slug: "creuse",
    region: "Nouvelle-Aquitaine",
    intro: "Guéret et Aubusson (cité de la tapisserie), le lac de Vassivière côté Creuse, l'étang des Landes, la vallée des Peintres autour de Crozant et Fresselines — un département rural et verdoyant entre Limousin et Berry.",
    seoTitle: "Où aller avec son chien en Creuse : Guéret, Aubusson, Vassivière",
    seoDescription: "Où aller avec son chien en Creuse : Guéret, Aubusson, lac de Vassivière, étang des Landes, vallée des Peintres autour de Crozant, balades et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien en Creuse",
  },
  {
    id: "19",
    nom: "Corrèze",
    slug: "correze",
    region: "Nouvelle-Aquitaine",
    intro: "Brive-la-Gaillarde et Tulle, les villages classés de Collonges-la-Rouge et Curemonte, le château de Turenne, les cascades de Gimel et la vallée de la Dordogne — entre plateau de Millevaches et bassin de Brive.",
    seoTitle: "Où aller avec son chien en Corrèze : Brive, Tulle, Collonges",
    seoDescription: "Où aller avec son chien en Corrèze : Brive-la-Gaillarde, Tulle, Collonges-la-Rouge, vallée de la Dordogne et lacs corréziens, balades et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien en Corrèze",
  },
  {
    id: "87",
    nom: "Haute-Vienne",
    slug: "haute-vienne",
    region: "Nouvelle-Aquitaine",
    intro: "Limoges et ses parcs, la cité martyre d'Oradour-sur-Glane, le lac de Saint-Pardoux, Rochechouart et son château météorite, Saint-Yrieix-la-Perche et le Pays de Nexon — entre vallées de la Vienne, de la Briance et de la Glane.",
    seoTitle: "Où aller avec son chien en Haute-Vienne : Limoges, Saint-Pardoux",
    seoDescription: "Où aller avec son chien en Haute-Vienne : Limoges, lac de Saint-Pardoux, Rochechouart, Saint-Yrieix-la-Perche et Nexon, balades et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien en Haute-Vienne",
  },
  {
    id: "86",
    nom: "Vienne",
    slug: "vienne",
    region: "Nouvelle-Aquitaine",
    intro: "Poitiers et ses parcs, le Futuroscope, Chauvigny et ses châteaux, Angles-sur-l'Anglin classé parmi les Plus Beaux Villages de France, Montmorillon et Châtellerault — entre vallées du Clain, de la Vienne et de la Gartempe.",
    seoTitle: "Où aller avec son chien en Vienne : Poitiers, Futuroscope",
    seoDescription: "Où aller avec son chien en Vienne : Poitiers, secteur du Futuroscope, Chauvigny, Châtellerault et Montmorillon, balades et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien en Vienne",
  },
  {
    id: "79",
    nom: "Deux-Sèvres",
    slug: "deux-sevres",
    region: "Nouvelle-Aquitaine",
    intro: "Niort et sa Sèvre Niortaise, le Marais Poitevin et sa Venise Verte entre Coulon, Arçais et Saint-Hilaire-la-Palud, Parthenay, Melle et Bressuire — canaux ombragés en barque, voies vertes et villages de la Gâtine.",
    seoTitle: "Où aller avec son chien en Deux-Sèvres : Niort, Marais Poitevin",
    seoDescription: "Où aller avec son chien en Deux-Sèvres : Niort, le Marais Poitevin (Coulon, Arçais), Parthenay, Melle et Bressuire, balades et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien en Deux-Sèvres",
  },
  {
    id: "16",
    nom: "Charente",
    slug: "charente",
    region: "Nouvelle-Aquitaine",
    intro: "Angoulême et sa bande dessinée, le vignoble de Cognac, La Rochefoucauld et son château, Confolens aux portes du Limousin — entre vallée de la Charente, eaux calmes et villages de pierre blanche.",
    seoTitle: "Où aller avec son chien en Charente : Angoulême, Cognac",
    seoDescription: "Où aller avec son chien en Charente : Angoulême, Cognac, La Rochefoucauld et Confolens, balades le long de la Charente et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien en Charente",
  },
  {
    id: "17",
    nom: "Charente-Maritime",
    slug: "charente-maritime",
    region: "Nouvelle-Aquitaine",
    intro: "La Rochelle et ses tours, l'Île de Ré et l'Île d'Oléron, Royan et la Côte de Beauté, Rochefort et l'estuaire de la Charente — un long littoral atlantique entre plages, marais et villages ostréicoles.",
    seoTitle: "Où aller avec son chien en Charente-Maritime",
    seoDescription: "Où aller avec son chien en Charente-Maritime : La Rochelle, Île de Ré, Île d'Oléron, Royan et Rochefort, plages, restaurants et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien en Charente-Maritime",
  },
  {
    id: "47",
    nom: "Lot-et-Garonne",
    slug: "lot-et-garonne",
    region: "Nouvelle-Aquitaine",
    intro: "Agen et sa ville natale de d'Artagnan, les bastides du Pays de Serres, Villeneuve-sur-Lot et Nérac — vergers, vignes et confluence de la Garonne et du Lot, entre bases de loisirs et villages de pierre blonde.",
    seoTitle: "Où aller avec son chien en Lot-et-Garonne : Agen",
    seoDescription: "Où aller avec son chien en Lot-et-Garonne : Agen, Villeneuve-sur-Lot, Nérac, Marmande et les bastides du Pays de Serres, bonnes adresses et bases de loisirs avec Coco.",
    seoH1: "Où aller avec son chien en Lot-et-Garonne",
  },
  {
    id: "24",
    nom: "Dordogne",
    slug: "dordogne",
    region: "Nouvelle-Aquitaine",
    intro: "Le Périgord et sa vallée de la Dordogne, Sarlat, les châteaux de La Roque-Gageac et Beynac, Périgueux et Brantôme — baignades de rivière et grands espaces entre Vézère et Isle.",
    seoTitle: "Où aller avec son chien en Dordogne : Sarlat, Périgueux",
    seoDescription: "Où aller avec son chien en Dordogne : baignades le long de la Dordogne et de la Vézère, Sarlat, Périgueux, Brantôme et les bastides du Périgord, avec Coco.",
    seoH1: "Où aller avec son chien en Dordogne",
  },
  {
    id: "33",
    nom: "Gironde",
    slug: "gironde",
    region: "Nouvelle-Aquitaine",
    intro: "Bordeaux, le bassin d'Arcachon, la Dune du Pilat, Lacanau et le vignoble de Saint-Émilion — entre océan Atlantique, lacs médocains et Garonne.",
    seoTitle: "Où aller avec son chien en Gironde : Bordeaux, Arcachon",
    seoDescription: "Où aller avec son chien en Gironde : bassin d'Arcachon, Dune du Pilat, Lacanau, Bordeaux et Saint-Émilion, plages et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien en Gironde",
  },
  {
    id: "40",
    nom: "Landes",
    slug: "landes",
    region: "Nouvelle-Aquitaine",
    intro: "Hossegor, Seignosse, Mimizan et Contis — de longues plages océanes, des lacs et étangs et la forêt des Landes de Gascogne, entre surf et grands espaces.",
    seoTitle: "Où aller avec son chien dans les Landes : plages, lacs",
    seoDescription: "Où aller avec son chien dans les Landes : plages d'Hossegor, de Seignosse et de Mimizan, lacs de Soustons et d'Hossegor, forêt des Landes de Gascogne, avec Coco.",
    seoH1: "Où aller avec son chien dans les Landes",
  },
  {
    id: "64",
    nom: "Pyrénées-Atlantiques",
    slug: "pyrenees-atlantiques",
    region: "Nouvelle-Aquitaine",
    intro: "La Côte Basque de Biarritz à Hendaye, le Pays Basque intérieur, Pau et les lacs de montagne du Béarn et de la vallée d'Ossau, aux portes du Parc national des Pyrénées.",
    seoTitle: "Où aller avec son chien dans les Pyrénées-Atlantiques",
    seoDescription: "Où aller avec son chien dans les Pyrénées-Atlantiques : plages de la Côte Basque, lacs d'Ayous et d'Artouste, Parc national des Pyrénées, Pau et Oloron, avec Coco.",
    seoH1: "Où aller avec son chien dans les Pyrénées-Atlantiques",
  },
  {
    id: "83",
    nom: "Var",
    slug: "var",
    region: "Provence-Alpes-Côte d'Azur",
    intro: "Le berceau de Coco Explore : Cavalaire, Saint-Tropez, Hyères, Toulon et toute la Provence Verte.",
    seoTitle: "Où aller avec son chien dans le Var : plages, balades, lacs",
    seoDescription: "Le Var avec son chien : plages autorisées, balades, lacs et bonnes adresses de Cavalaire à Toulon, en Provence Verte et sur la presqu'île de Giens, avec Coco.",
    seoH1: "Où aller avec son chien dans le Var",
  },
  {
    id: "06",
    nom: "Alpes-Maritimes",
    slug: "alpes-maritimes",
    region: "Provence-Alpes-Côte d'Azur",
    intro: "De Cannes à Menton en passant par Nice, l'arrière-pays niçois et le Mercantour.",
    seoTitle: "Où aller avec son chien dans les Alpes-Maritimes : plages",
    seoDescription: "Où aller avec son chien dans les Alpes-Maritimes : plages autorisées de Cannes à Menton, balades dans l'arrière-pays niçois et le Mercantour, avec Coco.",
    seoH1: "Où aller avec son chien dans les Alpes-Maritimes",
  },
  {
    id: "13",
    nom: "Bouches-du-Rhône",
    slug: "bouches-du-rhone",
    region: "Provence-Alpes-Côte d'Azur",
    intro: "Marseille, les Calanques, Aix-en-Provence et la Camargue.",
    seoTitle: "Où aller avec son chien dans les Bouches-du-Rhône : plages",
    seoDescription: "Où aller avec son chien dans les Bouches-du-Rhône : les îles du Frioul, les Calanques, Aix-en-Provence et la Camargue, bonnes adresses avec Coco Explore.",
    seoH1: "Où aller avec son chien dans les Bouches-du-Rhône",
  },
  {
    id: "84",
    nom: "Vaucluse",
    slug: "vaucluse",
    region: "Provence-Alpes-Côte d'Azur",
    intro: "Avignon, le Luberon, le mont Ventoux et les Dentelles de Montmirail — sans littoral, mais riche en balades.",
    seoTitle: "Où aller avec son chien dans le Vaucluse : balades, lacs",
    seoDescription: "Où aller avec son chien dans le Vaucluse : balades dans le Luberon, au mont Ventoux et dans les Dentelles de Montmirail, entre Avignon et Pertuis, avec Coco.",
    seoH1: "Où aller avec son chien dans le Vaucluse",
  },
  {
    id: "04",
    nom: "Alpes-de-Haute-Provence",
    slug: "alpes-de-haute-provence",
    region: "Provence-Alpes-Côte d'Azur",
    intro: "Les Gorges du Verdon, Digne-les-Bains et la vallée de l'Ubaye.",
    seoTitle: "Où aller avec son chien dans les Alpes-de-Haute-Provence",
    seoDescription: "Où aller avec son chien dans les Alpes-de-Haute-Provence : Gorges du Verdon, Digne-les-Bains et vallée de l'Ubaye, balades avec Coco comme guide.",
    seoH1: "Où aller avec son chien dans les Alpes-de-Haute-Provence",
  },
  {
    id: "05",
    nom: "Hautes-Alpes",
    slug: "hautes-alpes",
    region: "Provence-Alpes-Côte d'Azur",
    intro: "Le massif des Écrins, le Queyras, Briançon et le lac de Serre-Ponçon.",
    seoTitle: "Où aller avec son chien dans les Hautes-Alpes : balades",
    seoDescription: "Où aller avec son chien dans les Hautes-Alpes : massif des Écrins, Queyras, Briançon et lac de Serre-Ponçon, balades et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien dans les Hautes-Alpes",
  },
  {
    id: "34",
    nom: "Hérault",
    slug: "herault",
    region: "Occitanie",
    intro: "Montpellier, Sète, Cap d'Agde et La Grande-Motte — le littoral languedocien entre étangs, garrigue et grandes plages.",
    seoTitle: "Où aller avec son chien dans l'Hérault : plages, balades",
    seoDescription: "Où aller avec son chien dans l'Hérault : plages autorisées entre Sète et Cap d'Agde, balades en garrigue, bonnes adresses à Montpellier, avec Coco.",
    seoH1: "Où aller avec son chien dans l'Hérault",
  },
  {
    id: "30",
    nom: "Gard",
    slug: "gard",
    region: "Occitanie",
    intro: "Nîmes, le Pont du Gard, Uzès et les Cévennes — entre garrigue, gorges du Gardon et arrière-pays camarguais.",
    seoTitle: "Où aller avec son chien dans le Gard : balades, sites",
    seoDescription: "Où aller avec son chien dans le Gard : Pont du Gard, gorges du Gardon, Uzès, Nîmes et les Cévennes, balades et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien dans le Gard",
  },
  {
    id: "11",
    nom: "Aude",
    slug: "aude",
    region: "Occitanie",
    intro: "Carcassonne et sa Cité médiévale, Narbonne, Leucate et le vignoble des Corbières et du Minervois.",
    seoTitle: "Où aller avec son chien dans l'Aude : Carcassonne, Leucate",
    seoDescription: "Où aller avec son chien dans l'Aude : la Cité de Carcassonne, les plages de Leucate et Gruissan, les Corbières et le Minervois, avec Coco.",
    seoH1: "Où aller avec son chien dans l'Aude",
  },
  {
    id: "66",
    nom: "Pyrénées-Orientales",
    slug: "pyrenees-orientales",
    region: "Occitanie",
    intro: "Perpignan, Collioure et la Côte Vermeille, Céret, la Cerdagne et le massif du Canigó.",
    seoTitle: "Où aller avec son chien dans les Pyrénées-Orientales",
    seoDescription: "Où aller avec son chien dans les Pyrénées-Orientales : plages d'Argelès-sur-Mer et du Barcarès, Collioure, Céret, la Cerdagne et le Canigó, avec Coco.",
    seoH1: "Où aller avec son chien dans les Pyrénées-Orientales",
  },
  {
    id: "31",
    nom: "Haute-Garonne",
    slug: "haute-garonne",
    region: "Occitanie",
    intro: "Toulouse et son agglomération, le Comminges et le Luchonnais, entre Garonne et Pyrénées centrales.",
    seoTitle: "Où aller avec son chien en Haute-Garonne : Toulouse",
    seoDescription: "Où aller avec son chien en Haute-Garonne : Toulouse et ses caniparcs, le Lac de la Ramée, le Comminges et Bagnères-de-Luchon, avec Coco.",
    seoH1: "Où aller avec son chien en Haute-Garonne",
  },
  {
    id: "09",
    nom: "Ariège",
    slug: "ariege",
    region: "Occitanie",
    intro: "Foix, les Pyrénées ariégeoises, les grottes préhistoriques et les lacs de montagne du Couserans.",
    seoTitle: "Où aller avec son chien en Ariège : Pyrénées, lacs",
    seoDescription: "Où aller avec son chien en Ariège : Foix, les Pyrénées ariégeoises, les lacs de montagne du Couserans et les grottes, balades et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien en Ariège",
  },
  {
    id: "12",
    nom: "Aveyron",
    slug: "aveyron",
    region: "Occitanie",
    intro: "Rodez, le viaduc de Millau, les gorges du Tarn et les Causses.",
    seoTitle: "Où aller avec son chien en Aveyron : Millau, gorges du Tarn",
    seoDescription: "Où aller avec son chien en Aveyron : Rodez, le viaduc de Millau, les gorges du Tarn et les Causses, balades et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien en Aveyron",
  },
  {
    id: "32",
    nom: "Gers",
    slug: "gers",
    region: "Occitanie",
    intro: "Auch, les bastides gasconnes et le vignoble d'Armagnac, entre collines et vallée de la Baïse.",
    seoTitle: "Où aller avec son chien dans le Gers : Auch, Armagnac",
    seoDescription: "Où aller avec son chien dans le Gers : Auch, les bastides gasconnes, le vignoble d'Armagnac et la vallée de la Baïse, avec Coco comme guide.",
    seoH1: "Où aller avec son chien dans le Gers",
  },
  {
    id: "46",
    nom: "Lot",
    slug: "lot",
    region: "Occitanie",
    intro: "Cahors, Rocamadour, la vallée du Lot et le gouffre de Padirac.",
    seoTitle: "Où aller avec son chien dans le Lot : Cahors, Rocamadour",
    seoDescription: "Où aller avec son chien dans le Lot : Cahors, Rocamadour, la vallée du Lot et le gouffre de Padirac, balades et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien dans le Lot",
  },
  {
    id: "48",
    nom: "Lozère",
    slug: "lozere",
    region: "Occitanie",
    intro: "Mende, le mont Lozère, les gorges du Tarn et les Causses cévenols — le département le moins peuplé de France, entre grands espaces et nature préservée.",
    seoTitle: "Où aller avec son chien en Lozère : mont Lozère, gorges du Tarn",
    seoDescription: "Où aller avec son chien en Lozère : mont Lozère, gorges du Tarn, Causses cévenols et Mende, balades et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien en Lozère",
  },
  {
    id: "65",
    nom: "Hautes-Pyrénées",
    slug: "hautes-pyrenees",
    region: "Occitanie",
    intro: "Tarbes, Lourdes, le cirque de Gavarnie, la vallée d'Aure et les lacs de haute montagne.",
    seoTitle: "Où aller avec son chien dans les Hautes-Pyrénées : Gavarnie",
    seoDescription: "Où aller avec son chien dans les Hautes-Pyrénées : cirque de Gavarnie, vallée d'Aure, lacs pyrénéens et Lourdes, balades avec Coco comme guide.",
    seoH1: "Où aller avec son chien dans les Hautes-Pyrénées",
  },
  {
    id: "81",
    nom: "Tarn",
    slug: "tarn",
    region: "Occitanie",
    intro: "Albi et sa cité épiscopale, Castres, les gorges de l'Aveyron et le Sidobre.",
    seoTitle: "Où aller avec son chien dans le Tarn : Albi, Sidobre",
    seoDescription: "Où aller avec son chien dans le Tarn : Albi, Castres, les gorges de l'Aveyron et le Sidobre, balades et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien dans le Tarn",
  },
  {
    id: "82",
    nom: "Tarn-et-Garonne",
    slug: "tarn-et-garonne",
    region: "Occitanie",
    intro: "Montauban, Moissac et son cloître, la confluence du Tarn et de la Garonne.",
    seoTitle: "Où aller avec son chien en Tarn-et-Garonne : Montauban",
    seoDescription: "Où aller avec son chien en Tarn-et-Garonne : Montauban, Moissac, la vallée de l'Aveyron et la confluence Tarn-Garonne, avec Coco comme guide.",
    seoH1: "Où aller avec son chien en Tarn-et-Garonne",
  },
];
