export default [
  {
    id: "03",
    nom: "Allier",
    slug: "allier",
    region: "Auvergne-Rhône-Alpes",
    intro: "Moulins et Vichy, la forêt de Tronçais et ses étangs, les gorges de la Sioule, le château de Lapalisse, Montluçon et le canal de Berry — un département rural entre Bourbonnais et Sologne bourbonnaise, avec de grands espaces forestiers pour les balades.",
    seoTitle: "Où aller avec son chien dans l'Allier : Vichy, Moulins, Tronçais",
    seoDescription: "Où aller avec son chien dans l'Allier : Vichy, Moulins, forêt de Tronçais, gorges de la Sioule, Montluçon — balades, lacs et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien dans l'Allier",
  },
  {
    id: "01",
    nom: "Ain",
    slug: "ain",
    region: "Auvergne-Rhône-Alpes",
    intro: "Bourg-en-Bresse et la Bresse, le Bugey et ses lacs (Nantua, Genin), les gorges de l'Ain, la cité médiévale de Pérouges, les étangs de la Dombes et le Pays de Gex aux portes de Genève — un département aux visages très variés entre plaine, rivière et moyenne montagne.",
    seoTitle: "Où aller avec son chien dans l'Ain : Bourg-en-Bresse, Bugey, Pérouges",
    seoDescription: "Où aller avec son chien dans l'Ain : Bourg-en-Bresse, lac de Nantua, Bugey, Pérouges, Dombes, Pays de Gex — balades, plages et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien dans l'Ain",
  },
  {
    id: "23",
    nom: "Creuse",
    slug: "creuse",
    region: "Nouvelle-Aquitaine",
    intro: "Guéret et Aubusson (cité de la tapisserie), le lac de Vassivière côté Creuse, l'étang des Landes, la vallée des Peintres autour de Crozant et Fresselines — un département rural et verdoyant entre Limousin et Berry.",
    seoTitle: "Où aller avec son chien en Creuse : Guéret, Aubusson, Vassivière",
    seoDescription: "Où aller avec son chien en Creuse : Guéret, Aubusson, lac de Vassivière, étang des Landes, vallée des Peintres autour de Crozant, balades et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien en Creuse",
  },
  {
    id: "19",
    nom: "Corrèze",
    slug: "correze",
    region: "Nouvelle-Aquitaine",
    intro: "Brive-la-Gaillarde et Tulle, les villages classés de Collonges-la-Rouge et Curemonte, le château de Turenne, les cascades de Gimel et la vallée de la Dordogne — entre plateau de Millevaches et bassin de Brive.",
    seoTitle: "Où aller avec son chien en Corrèze : Brive, Tulle, Collonges",
    seoDescription: "Où aller avec son chien en Corrèze : Brive-la-Gaillarde, Tulle, Collonges-la-Rouge, vallée de la Dordogne et lacs corréziens, balades et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien en Corrèze",
  },
  {
    id: "87",
    nom: "Haute-Vienne",
    slug: "haute-vienne",
    region: "Nouvelle-Aquitaine",
    intro: "Limoges et ses parcs, la cité martyre d'Oradour-sur-Glane, le lac de Saint-Pardoux, Rochechouart et son château météorite, Saint-Yrieix-la-Perche et le Pays de Nexon — entre vallées de la Vienne, de la Briance et de la Glane.",
    seoTitle: "Où aller avec son chien en Haute-Vienne : Limoges, Saint-Pardoux",
    seoDescription: "Où aller avec son chien en Haute-Vienne : Limoges, lac de Saint-Pardoux, Rochechouart, Saint-Yrieix-la-Perche et Nexon, balades et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien en Haute-Vienne",
  },
  {
    id: "86",
    nom: "Vienne",
    slug: "vienne",
    region: "Nouvelle-Aquitaine",
    intro: "Poitiers et ses parcs, le Futuroscope, Chauvigny et ses châteaux, Angles-sur-l'Anglin classé parmi les Plus Beaux Villages de France, Montmorillon et Châtellerault — entre vallées du Clain, de la Vienne et de la Gartempe.",
    seoTitle: "Où aller avec son chien en Vienne : Poitiers, Futuroscope",
    seoDescription: "Où aller avec son chien en Vienne : Poitiers, secteur du Futuroscope, Chauvigny, Châtellerault et Montmorillon, balades et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien en Vienne",
  },
  {
    id: "79",
    nom: "Deux-Sèvres",
    slug: "deux-sevres",
    region: "Nouvelle-Aquitaine",
    intro: "Niort et sa Sèvre Niortaise, le Marais Poitevin et sa Venise Verte entre Coulon, Arçais et Saint-Hilaire-la-Palud, Parthenay, Melle et Bressuire — canaux ombragés en barque, voies vertes et villages de la Gâtine.",
    seoTitle: "Où aller avec son chien en Deux-Sèvres : Niort, Marais Poitevin",
    seoDescription: "Où aller avec son chien en Deux-Sèvres : Niort, le Marais Poitevin (Coulon, Arçais), Parthenay, Melle et Bressuire, balades et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien en Deux-Sèvres",
  },
  {
    id: "16",
    nom: "Charente",
    slug: "charente",
    region: "Nouvelle-Aquitaine",
    intro: "Angoulême et sa bande dessinée, le vignoble de Cognac, La Rochefoucauld et son château, Confolens aux portes du Limousin — entre vallée de la Charente, eaux calmes et villages de pierre blanche.",
    seoTitle: "Où aller avec son chien en Charente : Angoulême, Cognac",
    seoDescription: "Où aller avec son chien en Charente : Angoulême, Cognac, La Rochefoucauld et Confolens, balades le long de la Charente et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien en Charente",
  },
  {
    id: "17",
    nom: "Charente-Maritime",
    slug: "charente-maritime",
    region: "Nouvelle-Aquitaine",
    intro: "La Rochelle et ses tours, l'Île de Ré et l'Île d'Oléron, Royan et la Côte de Beauté, Rochefort et l'estuaire de la Charente — un long littoral atlantique entre plages, marais et villages ostréicoles.",
    seoTitle: "Où aller avec son chien en Charente-Maritime",
    seoDescription: "Où aller avec son chien en Charente-Maritime : La Rochelle, Île de Ré, Île d'Oléron, Royan et Rochefort, plages, restaurants et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien en Charente-Maritime",
  },
  {
    id: "47",
    nom: "Lot-et-Garonne",
    slug: "lot-et-garonne",
    region: "Nouvelle-Aquitaine",
    intro: "Agen et sa ville natale de d'Artagnan, les bastides du Pays de Serres, Villeneuve-sur-Lot et Nérac — vergers, vignes et confluence de la Garonne et du Lot, entre bases de loisirs et villages de pierre blonde.",
    seoTitle: "Où aller avec son chien en Lot-et-Garonne : Agen",
    seoDescription: "Où aller avec son chien en Lot-et-Garonne : Agen, Villeneuve-sur-Lot, Nérac, Marmande et les bastides du Pays de Serres, bonnes adresses et bases de loisirs avec Coco.",
    seoH1: "Où aller avec son chien en Lot-et-Garonne",
  },
  {
    id: "24",
    nom: "Dordogne",
    slug: "dordogne",
    region: "Nouvelle-Aquitaine",
    intro: "Le Périgord et sa vallée de la Dordogne, Sarlat, les châteaux de La Roque-Gageac et Beynac, Périgueux et Brantôme — baignades de rivière et grands espaces entre Vézère et Isle.",
    seoTitle: "Où aller avec son chien en Dordogne : Sarlat, Périgueux",
    seoDescription: "Où aller avec son chien en Dordogne : baignades le long de la Dordogne et de la Vézère, Sarlat, Périgueux, Brantôme et les bastides du Périgord, avec Coco.",
    seoH1: "Où aller avec son chien en Dordogne",
  },
  {
    id: "33",
    nom: "Gironde",
    slug: "gironde",
    region: "Nouvelle-Aquitaine",
    intro: "Bordeaux, le bassin d'Arcachon, la Dune du Pilat, Lacanau et le vignoble de Saint-Émilion — entre océan Atlantique, lacs médocains et Garonne.",
    seoTitle: "Où aller avec son chien en Gironde : Bordeaux, Arcachon",
    seoDescription: "Où aller avec son chien en Gironde : bassin d'Arcachon, Dune du Pilat, Lacanau, Bordeaux et Saint-Émilion, plages et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien en Gironde",
  },
  {
    id: "40",
    nom: "Landes",
    slug: "landes",
    region: "Nouvelle-Aquitaine",
    intro: "Hossegor, Seignosse, Mimizan et Contis — de longues plages océanes, des lacs et étangs et la forêt des Landes de Gascogne, entre surf et grands espaces.",
    seoTitle: "Où aller avec son chien dans les Landes : plages, lacs",
    seoDescription: "Où aller avec son chien dans les Landes : plages d'Hossegor, de Seignosse et de Mimizan, lacs de Soustons et d'Hossegor, forêt des Landes de Gascogne, avec Coco.",
    seoH1: "Où aller avec son chien dans les Landes",
  },
  {
    id: "64",
    nom: "Pyrénées-Atlantiques",
    slug: "pyrenees-atlantiques",
    region: "Nouvelle-Aquitaine",
    intro: "La Côte Basque de Biarritz à Hendaye, le Pays Basque intérieur, Pau et les lacs de montagne du Béarn et de la vallée d'Ossau, aux portes du Parc national des Pyrénées.",
    seoTitle: "Où aller avec son chien dans les Pyrénées-Atlantiques",
    seoDescription: "Où aller avec son chien dans les Pyrénées-Atlantiques : plages de la Côte Basque, lacs d'Ayous et d'Artouste, Parc national des Pyrénées, Pau et Oloron, avec Coco.",
    seoH1: "Où aller avec son chien dans les Pyrénées-Atlantiques",
  },
  {
    id: "83",
    nom: "Var",
    slug: "var",
    region: "Provence-Alpes-Côte d'Azur",
    intro: "Le berceau de Coco Explore : Cavalaire, Saint-Tropez, Hyères, Toulon et toute la Provence Verte.",
    seoTitle: "Où aller avec son chien dans le Var : plages, balades, lacs",
    seoDescription: "Le Var avec son chien : plages autorisées, balades, lacs et bonnes adresses de Cavalaire à Toulon, en Provence Verte et sur la presqu'île de Giens, avec Coco.",
    seoH1: "Où aller avec son chien dans le Var",
  },
  {
    id: "06",
    nom: "Alpes-Maritimes",
    slug: "alpes-maritimes",
    region: "Provence-Alpes-Côte d'Azur",
    intro: "De Cannes à Menton en passant par Nice, l'arrière-pays niçois et le Mercantour.",
    seoTitle: "Où aller avec son chien dans les Alpes-Maritimes : plages",
    seoDescription: "Où aller avec son chien dans les Alpes-Maritimes : plages autorisées de Cannes à Menton, balades dans l'arrière-pays niçois et le Mercantour, avec Coco.",
    seoH1: "Où aller avec son chien dans les Alpes-Maritimes",
  },
  {
    id: "13",
    nom: "Bouches-du-Rhône",
    slug: "bouches-du-rhone",
    region: "Provence-Alpes-Côte d'Azur",
    intro: "Marseille, les Calanques, Aix-en-Provence et la Camargue.",
    seoTitle: "Où aller avec son chien dans les Bouches-du-Rhône : plages",
    seoDescription: "Où aller avec son chien dans les Bouches-du-Rhône : les îles du Frioul, les Calanques, Aix-en-Provence et la Camargue, bonnes adresses avec Coco Explore.",
    seoH1: "Où aller avec son chien dans les Bouches-du-Rhône",
  },
  {
    id: "84",
    nom: "Vaucluse",
    slug: "vaucluse",
    region: "Provence-Alpes-Côte d'Azur",
    intro: "Avignon, le Luberon, le mont Ventoux et les Dentelles de Montmirail — sans littoral, mais riche en balades.",
    seoTitle: "Où aller avec son chien dans le Vaucluse : balades, lacs",
    seoDescription: "Où aller avec son chien dans le Vaucluse : balades dans le Luberon, au mont Ventoux et dans les Dentelles de Montmirail, entre Avignon et Pertuis, avec Coco.",
    seoH1: "Où aller avec son chien dans le Vaucluse",
  },
  {
    id: "04",
    nom: "Alpes-de-Haute-Provence",
    slug: "alpes-de-haute-provence",
    region: "Provence-Alpes-Côte d'Azur",
    intro: "Les Gorges du Verdon, Digne-les-Bains et la vallée de l'Ubaye.",
    seoTitle: "Où aller avec son chien dans les Alpes-de-Haute-Provence",
    seoDescription: "Où aller avec son chien dans les Alpes-de-Haute-Provence : Gorges du Verdon, Digne-les-Bains et vallée de l'Ubaye, balades avec Coco comme guide.",
    seoH1: "Où aller avec son chien dans les Alpes-de-Haute-Provence",
  },
  {
    id: "05",
    nom: "Hautes-Alpes",
    slug: "hautes-alpes",
    region: "Provence-Alpes-Côte d'Azur",
    intro: "Le massif des Écrins, le Queyras, Briançon et le lac de Serre-Ponçon.",
    seoTitle: "Où aller avec son chien dans les Hautes-Alpes : balades",
    seoDescription: "Où aller avec son chien dans les Hautes-Alpes : massif des Écrins, Queyras, Briançon et lac de Serre-Ponçon, balades et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien dans les Hautes-Alpes",
  },
  {
    id: "34",
    nom: "Hérault",
    slug: "herault",
    region: "Occitanie",
    intro: "Montpellier, Sète, Cap d'Agde et La Grande-Motte — le littoral languedocien entre étangs, garrigue et grandes plages.",
    seoTitle: "Où aller avec son chien dans l'Hérault : plages, balades",
    seoDescription: "Où aller avec son chien dans l'Hérault : plages autorisées entre Sète et Cap d'Agde, balades en garrigue, bonnes adresses à Montpellier, avec Coco.",
    seoH1: "Où aller avec son chien dans l'Hérault",
  },
  {
    id: "30",
    nom: "Gard",
    slug: "gard",
    region: "Occitanie",
    intro: "Nîmes, le Pont du Gard, Uzès et les Cévennes — entre garrigue, gorges du Gardon et arrière-pays camarguais.",
    seoTitle: "Où aller avec son chien dans le Gard : balades, sites",
    seoDescription: "Où aller avec son chien dans le Gard : Pont du Gard, gorges du Gardon, Uzès, Nîmes et les Cévennes, balades et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien dans le Gard",
  },
  {
    id: "11",
    nom: "Aude",
    slug: "aude",
    region: "Occitanie",
    intro: "Carcassonne et sa Cité médiévale, Narbonne, Leucate et le vignoble des Corbières et du Minervois.",
    seoTitle: "Où aller avec son chien dans l'Aude : Carcassonne, Leucate",
    seoDescription: "Où aller avec son chien dans l'Aude : la Cité de Carcassonne, les plages de Leucate et Gruissan, les Corbières et le Minervois, avec Coco.",
    seoH1: "Où aller avec son chien dans l'Aude",
  },
  {
    id: "66",
    nom: "Pyrénées-Orientales",
    slug: "pyrenees-orientales",
    region: "Occitanie",
    intro: "Perpignan, Collioure et la Côte Vermeille, Céret, la Cerdagne et le massif du Canigó.",
    seoTitle: "Où aller avec son chien dans les Pyrénées-Orientales",
    seoDescription: "Où aller avec son chien dans les Pyrénées-Orientales : plages d'Argelès-sur-Mer et du Barcarès, Collioure, Céret, la Cerdagne et le Canigó, avec Coco.",
    seoH1: "Où aller avec son chien dans les Pyrénées-Orientales",
  },
  {
    id: "31",
    nom: "Haute-Garonne",
    slug: "haute-garonne",
    region: "Occitanie",
    intro: "Toulouse et son agglomération, le Comminges et le Luchonnais, entre Garonne et Pyrénées centrales.",
    seoTitle: "Où aller avec son chien en Haute-Garonne : Toulouse",
    seoDescription: "Où aller avec son chien en Haute-Garonne : Toulouse et ses caniparcs, le Lac de la Ramée, le Comminges et Bagnères-de-Luchon, avec Coco.",
    seoH1: "Où aller avec son chien en Haute-Garonne",
  },
  {
    id: "09",
    nom: "Ariège",
    slug: "ariege",
    region: "Occitanie",
    intro: "Foix, les Pyrénées ariégeoises, les grottes préhistoriques et les lacs de montagne du Couserans.",
    seoTitle: "Où aller avec son chien en Ariège : Pyrénées, lacs",
    seoDescription: "Où aller avec son chien en Ariège : Foix, les Pyrénées ariégeoises, les lacs de montagne du Couserans et les grottes, balades et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien en Ariège",
  },
  {
    id: "12",
    nom: "Aveyron",
    slug: "aveyron",
    region: "Occitanie",
    intro: "Rodez, le viaduc de Millau, les gorges du Tarn et les Causses.",
    seoTitle: "Où aller avec son chien en Aveyron : Millau, gorges du Tarn",
    seoDescription: "Où aller avec son chien en Aveyron : Rodez, le viaduc de Millau, les gorges du Tarn et les Causses, balades et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien en Aveyron",
  },
  {
    id: "32",
    nom: "Gers",
    slug: "gers",
    region: "Occitanie",
    intro: "Auch, les bastides gasconnes et le vignoble d'Armagnac, entre collines et vallée de la Baïse.",
    seoTitle: "Où aller avec son chien dans le Gers : Auch, Armagnac",
    seoDescription: "Où aller avec son chien dans le Gers : Auch, les bastides gasconnes, le vignoble d'Armagnac et la vallée de la Baïse, avec Coco comme guide.",
    seoH1: "Où aller avec son chien dans le Gers",
  },
  {
    id: "46",
    nom: "Lot",
    slug: "lot",
    region: "Occitanie",
    intro: "Cahors, Rocamadour, la vallée du Lot et le gouffre de Padirac.",
    seoTitle: "Où aller avec son chien dans le Lot : Cahors, Rocamadour",
    seoDescription: "Où aller avec son chien dans le Lot : Cahors, Rocamadour, la vallée du Lot et le gouffre de Padirac, balades et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien dans le Lot",
  },
  {
    id: "48",
    nom: "Lozère",
    slug: "lozere",
    region: "Occitanie",
    intro: "Mende, le mont Lozère, les gorges du Tarn et les Causses cévenols — le département le moins peuplé de France, entre grands espaces et nature préservée.",
    seoTitle: "Où aller avec son chien en Lozère : mont Lozère, gorges du Tarn",
    seoDescription: "Où aller avec son chien en Lozère : mont Lozère, gorges du Tarn, Causses cévenols et Mende, balades et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien en Lozère",
  },
  {
    id: "65",
    nom: "Hautes-Pyrénées",
    slug: "hautes-pyrenees",
    region: "Occitanie",
    intro: "Tarbes, Lourdes, le cirque de Gavarnie, la vallée d'Aure et les lacs de haute montagne.",
    seoTitle: "Où aller avec son chien dans les Hautes-Pyrénées : Gavarnie",
    seoDescription: "Où aller avec son chien dans les Hautes-Pyrénées : cirque de Gavarnie, vallée d'Aure, lacs pyrénéens et Lourdes, balades avec Coco comme guide.",
    seoH1: "Où aller avec son chien dans les Hautes-Pyrénées",
  },
  {
    id: "81",
    nom: "Tarn",
    slug: "tarn",
    region: "Occitanie",
    intro: "Albi et sa cité épiscopale, Castres, les gorges de l'Aveyron et le Sidobre.",
    seoTitle: "Où aller avec son chien dans le Tarn : Albi, Sidobre",
    seoDescription: "Où aller avec son chien dans le Tarn : Albi, Castres, les gorges de l'Aveyron et le Sidobre, balades et bonnes adresses avec Coco.",
    seoH1: "Où aller avec son chien dans le Tarn",
  },
  {
    id: "82",
    nom: "Tarn-et-Garonne",
    slug: "tarn-et-garonne",
    region: "Occitanie",
    intro: "Montauban, Moissac et son cloître, la confluence du Tarn et de la Garonne.",
    seoTitle: "Où aller avec son chien en Tarn-et-Garonne : Montauban",
    seoDescription: "Où aller avec son chien en Tarn-et-Garonne : Montauban, Moissac, la vallée de l'Aveyron et la confluence Tarn-Garonne, avec Coco comme guide.",
    seoH1: "Où aller avec son chien en Tarn-et-Garonne",
  },
];
